PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?label ?type ?uri WHERE {
  {
    ?uri a ?type .
    ?uri rdfs:label ?l .
    BIND ( STR (?l) AS ?label ) # ignore the language tag
  }
  UNION
  {
    ?uri a ?type .
    ?uri foaf:name ?l .
    BIND ( STR (?l) AS ?label ) # ignore the language tag
  }
}
